# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: 徐浩然的博客
description: "dreamer worker geeker"
keywords: 'xhrjdzw,python,java,blog'
author:
  name: 徐浩然
  job_title: java开发工程师
  location: 北京
  email: xhrjdzw@126.com
  social_links:
    - name: github
      url: https://github.com/xhrjdzw/
    - name: stackoverflow
      url: https://xhrjdzw.github.io/Xhrboke.github.io/
home:
  section1: <h1>徐浩然的博客</h1>
  section2: <h2>A dreamer worker geeker</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://xhrjdzw.github.io/Xhrboke.github.io/" title="View on GitHub"></a></div>
blog:
  cc_license: # https://xhrjdzw.github.io/Xhrboke.github.io/
  cc_license_image: # Ahttps://xhrjdzw.github.io/Xhrboke.github.io/
  footer_content: A gem-based responsive simple texture styled Jekyll theme.

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
